orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

jobs:
  deploy-dev:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy-Dev.
          command: ssh -o  StrictHostKeyChecking=no ubuntu@18.224.40.236 './script.sh';
  
  
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          # context: myContext
          create-repo: false
          dockerfile: Env/Dev/Dockerfile
          no-output-timeout: 20m
          path: .
          # profile-name: myProfileName
          region: AWS_REGION
          repo: newrepo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: main
      - deploy-dev:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main
